### ISSUE TITLE
Coface attribute in Cell causing duplicates

### ISSUE THREAD

**Issue by bpraggastis** [kb1dds/pysheaf#3]
I replaced the Cell class constructor with:
```
    def __init__(self,dimension,compactClosure=True,cofaces=None, name=None):
        self.dimension=dimension
        self.compactClosure=compactClosure
        if cofaces != None:
            self.cofaces = cofaces
        else:
            self.cofaces = []
        self.name = name
```
The empty list in the original constructor linked the coface list of all the cells together if the cofaces were added after the cells were instantiated.

**Comment by kb1dds** [comment]
This sounds like a good enough idea to me.  I'll just commit it in myself.  Stand by!  Thanks!
